### ISSUE TITLE
shapes error and xtrace error

### ISSUE THREAD

**Issue by fptruong** [ianlmorgan/tweezepy#1]
I updated the module but I still run into "shapes is not defined" error when I try to use AV in smcalibration and "xtrace is not defined" error when I try to use PSD. Currently I'm on version 0.1.4.

**Comment by ianlmorgan** [comment]
I just updated it to version 0.1.5. Let me know if that fixes the problem.

**Comment by fptruong** [comment]
I updated to version 0.1.5 and I'm still getting the same errors. I followed exactly the example use codes.

**Comment by ianlmorgan** [comment]
I've tested both the PSD and AV fits on the documentation examples. Can you try updating the version again and retrying? If it doesn't work, can you copy and paste the error output?

**Comment by ianlmorgan** [comment]
Also, I fixed it so you don't have to copy over the smmcalibration and simulations files. I needed to add an __init__.py file.

**Comment by fptruong** [comment]
Seems like it's working now with the example uses. I will try out more with my actual data. Thanks for looking into this!

**Comment by ianlmorgan** [comment]
Thanks for checking!
